
### FILE GENERATED BY A LOCAL_PROGRAM        ###
### PLEASE DON'T MODIFY THIS FILE, WHICH     ###
### WILL BE RE-GENERATED                     ###

import i18n_setup as _i18n

from .mail.i18n import getMailI18n as _getMailI18n
from .icon.i18n import getIconI18n as _getIconI18n

LANGUAGES = []

def getUserI18n():
    i18n = _i18n.I18NTranslator()

    for i in LANGUAGES:
        parser = _i18n.I18NFileParser("./{}.i18n".format(i))
        i18n.addLanguage(parser.getLanguage())

    for subTranslator in [_getMailI18n(), _getIconI18n()]:
        i18n.loadFrom(subTranslator)

    return i18n

