
### FILE GENERATED BY A LOCAL_PROGRAM        ###
### PLEASE DON'T MODIFY THIS FILE, WHICH     ###
### WILL BE RE-GENERATED                     ###

import i18n_setup as _i18n

from .actions.i18n import getActionsI18n as _getActionsI18n

LANGUAGES = []

def getClientsI18n():
    i18n = _i18n.I18NTranslator()

    for i in LANGUAGES:
        parser = _i18n.I18NFileParser("./{}.i18n".format(i))
        i18n.addLanguage(parser.getLanguage())

    for subTranslator in [_getActionsI18n()]:
        i18n.loadFrom(subTranslator)

    return i18n

