
### FILE GENERATED BY A LOCAL_PROGRAM        ###
### PLEASE DON'T MODIFY THIS FILE, WHICH     ###
### WILL BE RE-GENERATED                     ###

import i18n_setup as _i18n

from .confile.i18n import getConfileI18n as _getConfileI18n

LANGUAGES = []

def getConfigurationI18n():
    i18n = _i18n.I18NTranslator()

    for i in LANGUAGES:
        parser = _i18n.I18NFileParser("./{}.i18n".format(i))
        i18n.addLanguage(parser.getLanguage())

    for subTranslator in [_getConfileI18n()]:
        i18n.loadFrom(subTranslator)

    return i18n

