
### FILE GENERATED BY A LOCAL_PROGRAM        ###
### PLEASE DON'T MODIFY THIS FILE, WHICH     ###
### WILL BE RE-GENERATED                     ###

import i18n_setup as _i18n

from .robots.i18n import getRobotsI18n as _getRobotsI18n
from .users.i18n import getUsersI18n as _getUsersI18n

LANGUAGES = ['fr_FR', 'en_US']

def getWorldI18n():
    i18n = _i18n.I18NTranslator()

    for i in LANGUAGES:
        parser = _i18n.I18NFileParser("./{}.i18n".format(i))
        i18n.addLanguage(parser.getLanguage())

    for subTranslator in [_getRobotsI18n(), _getUsersI18n()]:
        i18n.loadFrom(subTranslator)

    return i18n

