
### FILE GENERATED BY A LOCAL_PROGRAM        ###
### PLEASE DON'T MODIFY THIS FILE, WHICH     ###
### WILL BE RE-GENERATED                     ###

import i18n_setup as _i18n
import os as _os

from .clients.i18n import getClientsI18n as _getClientsI18n

LANGUAGES = ['fr_FR', 'en_US']

def getServerI18n():
    i18n = _i18n.I18NTranslator()

    for i in LANGUAGES:
        parser = _i18n.I18NFileParser(_os.path.abspath("./{}.i18n".format(i)))
        i18n.addLanguage(parser.getLanguage())

    for subTranslator in [_getClientsI18n()]:
        i18n.loadFrom(subTranslator)

    return i18n

